-- Tạo bảng classroom
CREATE TABLE public.classroom (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    classroom_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    note TEXT NULL DEFAULT ''::TEXT,
    CONSTRAINT classroom_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Tạo trigger handle_updated_at trước khi cập nhật bảng classroom
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Tạo trigger để gọi hàm cập nhật updated_at
CREATE TRIGGER handle_updated_at
BEFORE UPDATE ON public.classroom
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();