CREATE TABLE public.school_timetable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    date DATE NULL,
    subject_id BIGINT NULL,
    classroom_id BIGINT NULL,
    teacher_id BIGINT NOT NULL,
    status SMALLINT NULL DEFAULT '3'::SMALLINT,
    key TEXT NULL,
    CONSTRAINT school_timetable_pkey PRIMARY KEY (id),
    CONSTRAINT school_timetable_classroom_id_fkey FOREIGN KEY (classroom_id) REFERENCES public.classroom (id) ON DELETE CASCADE,
    CONSTRAINT school_timetable_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.session (id) ON DELETE CASCADE,
    CONSTRAINT school_timetable_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subject (id) ON DELETE CASCADE,
    CONSTRAINT school_timetable_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public."user" (id) ON DELETE CASCADE
) TABLESPACE pg_default;